[build]
  publish = "public"

[functions]
  node_bundler = "esbuild"

[build.environment]
  HUGO_VERSION = "0.71.1"

[context.deploy-preview]
  command = "npm install && npm run deploy"

[context.branch-deploy]
  command = "npm install && npm run deploy:branch"

[[headers]]
  for = "/index.json"
  [headers.values]
  Access-Control-Allow-Origin = "*"

# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

  # # optional, fails build when a category is below a threshold
  # [plugins.inputs.thresholds]
  #   performance = 0.9
  #   accessibility = 0.9
  #   best-practices = 0.9
  #   seo = 0.9
  #   pwa = 0.9

  # optional, deploy the lighthouse report to a path under your site
  # [plugins.inputs]
  #   output_path = "reports/lighthouse.html"